main: rush.login.Main
version: 1.0
name: Login

commands:
  # Não adicione novas aliases nos comandos!!!!
  login:
    description: Efetua o login no servidor.]
  register:
    description: Efetua o cadastro no servidor.
  unregister:
    description: Deleta um player do banco de dados
    aliases: [desregistrar]
    permission: login.admin
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  changepassword:
    description: Altera a senha cadastrada.
    aliases: [trocarsenha]
